defaults:
# - base: test
- _self_

hydra:
  sweeper:
    params:
      basic.channels: range(5)

        # - [1,2,3]
        # - [1,3,4]
#       channels: (1, 2, 3),(1, 2, 4),(1, 2, 5),(1, 3, 4),(1, 3, 5),(1, 4, 5),(2, 3, 4),(2, 3, 5),(2, 4, 5),(3, 4, 5)
# Path: biomed/conf/config.yam
basic:
  # experiment_name: test_0
  channels_lists: [[1,2,3],[1,2,4],[1,2,5],[1,3,4],[1,3,5],[1,4,5],[2,3,4],[2,3,5],[2,4,5],[3,4,5]]
  experiment_name: test_3
  channels: [3,4,5]
  dataset_path: dset
  epochs: 10
  train_val_split: 0.8
  batch_size: 128
  normalize_bw: True
  normalize_bw_non_one: True
  normalize_color: False
  convert_to_uint8: True
  segmentation_channel: 1
  input_shape: [224, 224]
  image_shape: [1080, 1080]
  n_channels: 3
  padding: rescale #value
  padding_value: 0
  weights: 'imagenet' # or null
  d: 80
  channel_3_avg_12: False
  shuffle_dataset: True
  model: ResNet50