defaults:
# - base: test
- _self_

hydra:
  sweeper:
    params:
      # basic.channels: range(0,11)
      basic.model.linear_1: 64,128,256,512
      basic.model.dropout_1: 0.1,0.2,0.3,0.4,0.5

        # - [1,2,3]
        # - [1,3,4]
#       channels: (1, 2, 3),(1, 2, 4),(1, 2, 5),(1, 3, 4),(1, 3, 5),(1, 4, 5),(2, 3, 4),(2, 3, 5),(2, 4, 5),(3, 4, 5)
# Path: biomed/conf/config.yam
basic:
  # experiment_name: test_0
  channels_lists: [[1,2,3],[1,2,4],[1,2,5],[1,3,4],[1,3,5],[1,4,5],[2,3,4],[2,3,5],[2,4,5],[3,4,5]]
  experiment_name: test_7_architecture
  channels: 0
  dataset_path: dset
  normalize_ch_color: True
  freeze_backbone: True
  epochs: 50
  batch_size: 1024
  normalize_bw: True
  normalize_bw_non_one: True
  normalize_color: False
  convert_to_uint8: True
  segmentation_channel: 1
  input_shape: [224, 224]
  image_shape: [1080, 1080]
  n_channels: 3
  padding: rescale #value
  padding_value: 0
  weights: 'imagenet' # or null
  d: 75
  channel_3_avg_12: False
  shuffle_dataset: True
  model: ResNet50
  splits:
    test: 0.2
    val: 0.2
  model:
    linear_1: 256
    dropout_1: 0.2
